export const activities = [
    {
        id: 1,
        title: "Eagle Flight (Zipline)",
        category: "Aerial Thrills",
        description: "Climb a wooden ladder, cross a 38-foot suspension bridge, and experience an exciting zipline ride with panoramic views of the adventure park before landing on the Multi Activity Tower.",
        image: "https://images.unsplash.com/photo-1599930113854-d6d7fd521f10?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 2,
        title: "Sky Cycle",
        category: "Aerial Thrills",
        description: "Experience the thrill of riding India’s longest and highest Sky Cycle in Rishikesh. Ride high above the ground while enjoying breathtaking views and an unforgettable adventure.",
        image: "https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 3,
        title: "Sky Cycle (Kids)",
        category: "Aerial Thrills",
        description: "A kid-friendly version of the Sky Cycle designed to provide a safe and exciting elevated cycling experience for young adventurers.",
        image: "https://images.unsplash.com/photo-1603138461767-e6f7725a3d76?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 4,
        title: "Superman Shot",
        category: "Aerial Thrills",
        description: "Feel the sensation of flying like a superhero as you’re launched through the air in one of the park’s signature adrenaline-pumping attractions.",
        image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 5,
        title: "Giant Swing",
        category: "Aerial Thrills",
        description: "Swing through the air with incredible speed and height while enjoying a thrilling free-fall sensation.",
        image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 6,
        title: "Reverse Bungee",
        category: "Aerial Thrills",
        description: "Also known as the Sling Shot, this ride catapults participants high into the sky, creating an exhilarating experience.",
        image: "https://images.unsplash.com/photo-1563841930606-67e2b6c387ea?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 7,
        title: "Rock Climbing",
        category: "Climbing & Ropes",
        description: "Challenge your strength and determination by climbing a rock wall with professional safety equipment.",
        image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 8,
        title: "Rock Climbing (50 Feet)",
        category: "Climbing & Ropes",
        description: "Scale a 50-foot climbing wall designed to test endurance, balance, and confidence.",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 9,
        title: "Go Kart (Adult)",
        category: "Racing & Go-Kart",
        description: "Drive eco-friendly electric go-karts on a specially designed racing track.",
        image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 10,
        title: "Go Kart (Adult Couple)",
        category: "Racing & Go-Kart",
        description: "Enjoy an electric go-kart ride together with a companion.",
        image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 11,
        title: "Go Kart (Kids)",
        category: "Racing & Go-Kart",
        description: "A fun and safe electric go-kart experience designed for young racers.",
        image: "https://images.unsplash.com/photo-1596701062351-df1f8ad36785?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 12,
        title: "Couple Go-Kart",
        category: "Racing & Go-Kart",
        description: "A shared racing experience for couples on the dedicated circuit.",
        image: "https://images.unsplash.com/photo-1534067783941-51c9c23eccfd?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 13,
        title: "Tandem Sky Cycle",
        category: "Aerial Thrills",
        description: "Ride a Sky Cycle together with a partner for a unique aerial adventure.",
        image: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 14,
        title: "Tandem Zipline",
        category: "Aerial Thrills",
        description: "Experience ziplining alongside a partner with scenic aerial views.",
        image: "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 15,
        title: "Sky Roller",
        category: "Aerial Thrills",
        description: "An elevated rolling adventure combining movement, balance, and panoramic views.",
        image: "https://images.unsplash.com/photo-1572508589584-94d778209eb9?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 16,
        title: "Rappelling",
        category: "Climbing & Ropes",
        description: "Descend a vertical surface using ropes and safety gear under expert supervision.",
        image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 17,
        title: "Slithering",
        category: "Climbing & Ropes",
        description: "Learn controlled rope descent techniques while navigating steep surfaces.",
        image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 18,
        title: "Commando Net Climbing",
        category: "Climbing & Ropes",
        description: "Test your agility and upper-body strength on a military-style cargo net.",
        image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 19,
        title: "Tyre Wall Climbing",
        category: "Climbing & Ropes",
        description: "Climb a wall made of interconnected tyres that challenges coordination and grip strength.",
        image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 20,
        title: "Rope Course",
        category: "Climbing & Ropes",
        description: "Navigate more than 30 rope obstacles designed to test physical ability and mental focus.",
        image: "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 21,
        title: "Multi Activities Tower & Rope Course",
        category: "Climbing & Ropes",
        description: "A combination of climbing elements, rope obstacles, and adventure challenges.",
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 22,
        title: "Full Rope Course (30+ Activities)",
        category: "Climbing & Ropes",
        description: "Complete a series of over 30 rope-based adventure challenges.",
        image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 23,
        title: "Paint Ball",
        category: "Combos & Access",
        description: "Enjoy a team-based tactical game in an exciting outdoor battlefield environment.",
        image: "https://images.unsplash.com/photo-1507208773393-40d9fc670acf?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 24,
        title: "Zip Zap Zoom",
        category: "Combos & Access",
        description: "A multi-adventure package combining several aerial attractions.",
        image: "https://images.unsplash.com/photo-1533240332313-0db49b439ad3?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 25,
        title: "Sky Tour Combo",
        category: "Combos & Access",
        description: "A bundled experience featuring multiple signature adventure activities.",
        image: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=600&auto=format&fit=crop&q=80",
    },
    {
        id: 26,
        title: "Full Park Access (42+ Activities)",
        category: "Combos & Access",
        description: "An all-access pass allowing visitors to enjoy more than 42 adventure activities.",
        image: "https://images.unsplash.com/photo-1508873535684-277a3cbcc4e8?w=600&auto=format&fit=crop&q=80",
    }
];

export const categories = ["All", "Aerial Thrills", "Climbing & Ropes", "Racing & Go-Kart", "Combos & Access"];
